// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaghKSAoSOcL2_bwrWjASy7BmCaKdlT_A',
    appId: '1:685449083250:android:ac541903134e1e587505eb',
    messagingSenderId: '685449083250',
    projectId: 'revee-cms',
    storageBucket: 'revee-cms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3CrQPh14z8mMUsygOpbvWjhmZ50g0TQ4',
    appId: '1:685449083250:ios:20421edafdbdc65f7505eb',
    messagingSenderId: '685449083250',
    projectId: 'revee-cms',
    storageBucket: 'revee-cms.appspot.com',
    androidClientId: '685449083250-akgfjr4eqnpu7390opcbjsd70bnspg0i.apps.googleusercontent.com',
    iosClientId: '685449083250-dl2j3thpv7cjs7fp04udrqca1mcb0v0k.apps.googleusercontent.com',
    iosBundleId: 'it.revee',
  );
}
